# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouldersX', models.CharField(max_length=5)),
                ('shouldersY', models.CharField(max_length=5)),
                ('bustX', models.CharField(max_length=5)),
                ('bustY', models.CharField(max_length=5)),
                ('underbustX', models.CharField(max_length=5)),
                ('underbustY', models.CharField(max_length=5)),
                ('underarm_to_waistX', models.CharField(max_length=5)),
                ('underarm_to_waistY', models.CharField(max_length=5)),
                ('underbust_to_waistX', models.CharField(max_length=5)),
                ('underbust_to_waistY', models.CharField(max_length=5)),
                ('waistX', models.CharField(max_length=5)),
                ('waistY', models.CharField(max_length=5)),
                ('waist_to_hipX', models.CharField(max_length=5)),
                ('waist_to_hipY', models.CharField(max_length=5)),
                ('hip_to_kneeX', models.CharField(max_length=5)),
                ('hip_to_kneeY', models.CharField(max_length=5)),
                ('hip_to_ankleX', models.CharField(max_length=5)),
                ('hip_to_ankleY', models.CharField(max_length=5)),
            ],
        ),
    ]
