# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='bust',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='hip_to_ankle',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='hip_to_knee',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='shoulders',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='underarm_to_waist',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='underbust',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='underbust_to_waist',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='waist',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurements',
            name='waist_to_hip',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
