# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_generator', '0002_auto_20160523_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='bustX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='bustY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='hip_to_ankleX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='hip_to_ankleY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='hip_to_kneeX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='hip_to_kneeY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='shouldersX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='shouldersY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underarm_to_waistX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underarm_to_waistY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underbustX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underbustY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underbust_to_waistX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='underbust_to_waistY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='waistX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='waistY',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='waist_to_hipX',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='waist_to_hipY',
        ),
    ]
