# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_generator', '0007_auto_20160523_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='hip_to_crotch',
        ),
    ]
