# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_generator', '0008_remove_measurements_hip_to_crotch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='bust',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='hip',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='hip_to_ankle',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='hip_to_knee',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='neck_to_bust',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='shoulders',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='underarm_to_waist',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='underbust',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='underbust_to_waist',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='waist',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='waist_to_hip',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
