# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_generator', '0009_auto_20160523_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_length', models.DecimalField(decimal_places=3, max_digits=5)),
                ('center_front_length', models.DecimalField(decimal_places=3, max_digits=5)),
                ('shoulder_tip', models.DecimalField(decimal_places=3, max_digits=5)),
                ('shoulder_length', models.DecimalField(decimal_places=3, max_digits=5)),
                ('across_shoulder', models.DecimalField(decimal_places=3, max_digits=5)),
                ('armhole_depth', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bust_depth', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bust_span', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bust_arc', models.DecimalField(decimal_places=3, max_digits=5)),
                ('shoulder_slope', models.DecimalField(decimal_places=3, max_digits=5)),
                ('side_seam_length', models.DecimalField(decimal_places=3, max_digits=5)),
                ('waist_arc', models.DecimalField(decimal_places=3, max_digits=5)),
                ('dart_placement', models.DecimalField(decimal_places=3, max_digits=5)),
                ('short', models.BooleanField()),
            ],
        ),
    ]
